### ISSUE TITLE
Details of tasks created prior to v1.0.5 do not show up

### ISSUE THREAD

**Issue by derick-dsouza** [february-labs/devgpt-releases#17] opened 2023-08-29 12:25 UTC
The side bar lists all of the my previous tasks, however, when I click on any of the tasks, it shows details of only those tasks that have been created in v1.0.5.

**Comment by tom-lewis-code** [comment] 2023-09-01 20:37
Hey Derick, I'm sorry but this issue can't be fixed retrospectively. I've marked it as wontfix, but this shouldn't be an issue in the future (example moving from 1.0.6 to 1.0.5).

This was only caused by our swapping of schema for how we store code in V1.0.5

Thank you for your report! :)

**Closed by tom-lewis-code** 2023-09-01 20:37 UTC
