### ISSUE TITLE
Setup with Dolphin 

### ISSUE THREAD

**Issue by hapees** [february-labs/devgpt-releases#12] opened 2023-08-21 22:19 UTC
DevGPT_1.0.3_amd64.snap setup
Only Boxes are being displayed as characters in Dolphin 
From Quick Settings - > Select a Directory. ..

**Comment by tom-lewis-code** [comment] 2023-08-22 07:40
Hey @hapees, thank you for reporting this! Are you able to provide some more detail about the issue and/or a screenshot? I'll take a look at this asap :)

**Comment by tom-lewis-code** [comment] 2023-08-25 19:52
Hey @hapees, I'm going to close this issue for now for cleanliness but if you have any more details on the issue you'd like to share you can comment, or get in touch with me via discord :)

Thank you for your feedback, I hope we can get this fixed for you!

**Closed by tom-lewis-code** 2023-08-25 19:52 UTC
Labels: Needs More Detail

**Comment by hapees** [comment] 2023-08-25 20:33
sorry for the delayed answer 
I have attached the screen shots with clicks in that following order :-)

![Screenshot_20230825_222656](https://github.com/february-labs/devgpt-releases/assets/628783/9e4ffb75-812b-494a-98ff-bab595eeb08d)
![Screenshot_20230825_222744](https://github.com/february-labs/devgpt-releases/assets/628783/1c31b0d9-4ac8-4218-be63-a1328767154e)
![Screenshot_20230825_222809](https://github.com/february-labs/devgpt-releases/assets/628783/aea3428a-837d-41da-bebb-cf6ff53154f7)

**Comment by hapees** [comment] 2023-08-27 12:35
Looks like ist's snap problem..

[https://forum.snapcraft.io/t/snapped-app-not-loading-fonts-on-fedora-and-arch/12484/14](url)

**Comment by tom-lewis-code** [comment] 2023-08-31 09:05
Hey @hapees I can't thank you enough for finding that forum, gave me a good understanding of it. I had a seperate user demonstrate this for me and I now understand the issue. This is now a duplicate of #24 but thank you very much for the original report!
